# Generated by Django 4.1.7 on 2023-04-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circuito',
            new_name='Circuit',
        ),
        migrations.RenameModel(
            old_name='Piloto',
            new_name='Driver',
        ),
        migrations.RenameField(
            model_name='circuit',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='nombre',
            new_name='name',
        ),
    ]
