# Generated by Django 4.1.7 on 2023-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_circuito_circuit_rename_piloto_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
